@IsTest
public with sharing class AccountTriggerHandlerTest {
/*
    @IsTest
    static void phoneFormatTest(){
		List<Account> accList = new List<Account>();
        Account acc1 = new Account(RecordTypeId = Schema.SobjectType.Account.getRecordTypeInfosByDeveloperName().get('Travel_Detail').getRecordTypeId());
        Account acc2 = new Account(Phone='1111111');
        Account acc3 = new Account(Phone='11111111111');
        
        accList.add(acc1);
        accList.add(acc2);
        accList.add(acc3);

        Test.startTest();
        
            Database.SaveResult[] sr = Database.insert(accList, false);

        Test.stopTest();
        

    }
*/
}